In [1]:
import streamlit as st
from streamlit_jupyter import StreamlitPatcher, tqdm
StreamlitPatcher().jupyter()  # register streamlit with jupyter-compatible wrappers
import sys; sys.path.append('..')
from osp import *
pd.options.display.max_colwidth = 200
pd.options.display.max_rows = 20

In [2]:
df_preds = get_current_pred_probs()
df_preds_sample = df_preds.groupby('target').sample(100)
ids = df_preds_sample.index.tolist()

In [4]:
dfx=df_preds.query('comparison >= "2000"')
# dfx = df_preds.query('target == "Philosophy"')
# dfx

In [3]:
printm(describe_slice_probs(ids))

- **Literature** (n=591) was predicted successfully **89.7%** of the time (across 10 model
runs each of 5 comparisons), with an average confidence of **86.2%**.

- **Philosophy** (n=584) was predicted successfully **85.3%** of the time (across 10 model
runs each of 5 comparisons), with an average confidence of **83.6%**.

- Each run of the model had **2,000** samples divided evenly.

- The best performing comparison was **2000-2025** (93.3% confidence),  with a success
rate of **97.0%**.

- The worst performing comparison was **1925-1950** (70.0% confidence), with a success
rate of **71.7%**.

In [10]:
get_slice_info_df_preds(dfx.index.tolist())

,comparison,predict_type,prob_correct,perc_correct,num_correct,num_runs,support,num_samples
target,,,,,,,,
Literature,1900-1925 Philosophy vs 1900-1925 Literature,cv,0.857448,0.888298,668,10,1504.0,752
Literature,1900-1925 Philosophy vs 1900-1925 Literature,unseen,0.719473,0.741998,10014,10,1504.0,13496
Literature,1925-1950 Philosophy vs 1925-1950 Literature,cv,0.888963,0.914643,1243,10,2000.0,1359
Literature,1925-1950 Philosophy vs 1925-1950 Literature,unseen,0.670708,0.685483,9727,10,2000.0,14190
Literature,1950-1975 Philosophy vs 1950-1975 Literature,cv,0.868743,0.905020,2001,10,2000.0,2211
Literature,1950-1975 Philosophy vs 1950-1975 Literature,unseen,0.816842,0.859530,12244,10,2000.0,14245
Literature,1975-2000 Philosophy vs 1975-2000 Literature,cv,0.871858,0.906886,3253,10,2000.0,3587
Literature,1975-2000 Philosophy vs 1975-2000 Literature,unseen,0.854363,0.902934,12865,10,2000.0,14248
Literature,2000-2025 Philosophy vs 2000-2025 Literature,cv,0.918025,0.949047,5774,10,2000.0,6084
Literature,2000-2025 Philosophy vs 2000-2025 Literature,unseen,0.912256,0.943571,13444,10,2000.0,14248
Philosophy,1900-1925 Philosophy vs 1900-1925 Literature,cv,0.854040,0.902315,1247,10,1504.0,1382
Philosophy,1900-1925 Philosophy vs 1900-1925 Literature,unseen,0.795979,0.840841,24249,10,1504.0,28839
Philosophy,1925-1950 Philosophy vs 1925-1950 Literature,cv,0.888480,0.921569,2068,10,2000.0,2244
Philosophy,1925-1950 Philosophy vs 1925-1950 Literature,unseen,0.898533,0.926979,26735,10,2000.0,28841
Philosophy,1950-1975 Philosophy vs 1950-1975 Literature,cv,0.865943,0.906165,2984,10,2000.0,3293
Philosophy,1950-1975 Philosophy vs 1950-1975 Literature,unseen,0.891667,0.928160,26770,10,2000.0,28842
Philosophy,1975-2000 Philosophy vs 1975-2000 Literature,cv,0.874448,0.909072,4439,10,2000.0,4883
Philosophy,1975-2000 Philosophy vs 1975-2000 Literature,unseen,0.860472,0.889120,25644,10,2000.0,28842
Philosophy,2000-2025 Philosophy vs 2000-2025 Literature,cv,0.917889,0.936384,11952,10,2000.0,12764
Philosophy,2000-2025 Philosophy vs 2000-2025 Literature,unseen,0.833487,0.855142,24664,10,2000.0,28842

In [11]:

def get_slice_info(slice_id, df_preds=None):
    out_d = {}
    if df_preds is None:
        df_preds = get_df_preds()
    
    return df_preds

In [12]:
for id,x in STASH_SLICES_NLP.items():
    break

In [13]:
get_slice_info(id)

,prob_Literature,prob_Philosophy,support,run,predict_type,comparison
id,,,,,,
lit/456903__06,0.021961,0.978039,1504,0,cv,1900-1925 Philosophy vs 1900-1925 Literature
lit/3713754__02,0.977459,0.022541,1504,0,cv,1900-1925 Philosophy vs 1900-1925 Literature
lit/457155__03,0.996810,0.003190,1504,0,cv,1900-1925 Philosophy vs 1900-1925 Literature
lit/433422__05,0.991444,0.008556,1504,0,cv,1900-1925 Philosophy vs 1900-1925 Literature
lit/456699__05,0.161604,0.838396,1504,0,cv,1900-1925 Philosophy vs 1900-1925 Literature
...,...,...,...,...,...,...
lit/27760277__03,0.979312,0.020688,2000,9,unseen,2000-2025 Philosophy vs 2000-2025 Literature
phil/10.2307/2025409__04,0.000012,0.999988,2000,9,unseen,2000-2025 Philosophy vs 2000-2025 Literature
phil/10.2307/2953730__03,0.010580,0.989420,2000,9,unseen,2000-2025 Philosophy vs 2000-2025 Literature
lit/468421__06,0.416730,0.583270,2000,9,unseen,2000-2025 Philosophy vs 2000-2025 Literature
phil/10.2307/2185617__06,0.320571,0.679429,2000,9,unseen,2000-2025 Philosophy vs 2000-2025 Literature

In [14]:
display_slice_predictions(doc, 'weight_z', 'word')

NameError: name 'display_slice_predictions' is not defined