In [1]:
import sys; sys.path.append('..')
from osp import *
pd.options.display.max_colwidth = 200
pd.options.display.max_rows = 20

In [3]:
# get_preds_feats(COMPARISONS[0], force=True)
# df_preds, df_feats, d_models = get_preds_feats()

In [4]:
# df_feats['feat_type'] = df_feats['feature'].str.split('_').str[0]
# df_feats['weight_abs'] = df_feats['weight'].abs()

In [5]:
# df_feats.groupby('feat_type').mean(numeric_only=True).sort_values('weight_abs',ascending=False)

In [6]:
get_dashboard_df_feats()

,feat_desc,W1925,W1950,W1975,W2000,vals_W,P1925,P1950,P1975,P2000,...,L1925,L1950,L1975,L2000,vals_L,P1925/L1925,P1950/L1950,P1975/L1975,P2000/L2000,vals_P/L
feature,,,,,,,,,,,,,,,,,,,,,
deprel_acl,Clausal modifier of noun (adnominal clause),0.096,0.104,0.242,0.330,"[-0.195, 0.096, 0.104, 0.242, 0.33]",-0.141,0.058,0.248,0.333,...,-0.561,-0.490,-0.318,-0.235,"[-0.544, -0.561, -0.49, -0.318, -0.235]",-1.381,NaN,NaN,NaN,"[-0.6052171080532431, -1.3809610151445282, nan, nan, nan]"
deprel_acl:relcl,Relative clause modifier,0.260,-0.067,0.031,0.227,"[-0.04, 0.26, -0.067, 0.031, 0.227]",0.076,0.136,0.130,0.063,...,-0.617,-0.321,-0.014,-0.044,"[-0.63, -0.617, -0.321, -0.014, -0.044]",NaN,NaN,NaN,NaN,"[nan, nan, nan, nan, nan]"
deprel_advcl,Adverbial clause modifier,0.138,-0.036,-0.129,0.114,"[-0.009, 0.138, -0.036, -0.129, 0.114]",-0.171,0.145,0.184,0.320,...,-0.569,-0.409,-0.300,-0.274,"[-0.65, -0.569, -0.409, -0.3, -0.274]",-1.202,NaN,NaN,NaN,"[-1.4865397761109467, -1.2022168776236708, nan, nan, nan]"
deprel_advcl:relcl,Adverbial relative clause modifier,0.140,0.139,0.046,-0.046,"[-0.009, 0.14, 0.139, 0.046, -0.046]",-0.238,-0.067,0.065,0.315,...,-0.312,-0.276,-0.194,-0.093,"[-0.262, -0.312, -0.276, -0.194, -0.093]",-0.271,-1.416,NaN,NaN,"[-0.10028436262596578, -0.2707325141380077, -1.4157082463261839, nan, nan]"
deprel_advmod,Adverbial modifier,-0.133,0.505,1.580,0.654,"[-0.217, -0.133, 0.505, 1.58, 0.654]",-0.003,0.168,0.221,0.299,...,-0.478,-0.367,-0.363,-0.499,"[-0.448, -0.478, -0.367, -0.363, -0.499]",-5.071,NaN,NaN,NaN,"[nan, -5.070998443823346, nan, nan, nan]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ttr_ADV,,0.044,-0.073,-0.028,0.018,"[-0.265, 0.044, -0.073, -0.028, 0.018]",0.334,0.030,-0.095,-0.311,...,0.021,0.182,0.273,0.229,"[-0.044, 0.021, 0.182, 0.273, 0.229]",2.767,-1.803,NaN,NaN,"[nan, 2.7666185552532774, -1.80280930541464, nan, nan]"
ttr_NOUN,,-0.701,-0.525,-0.423,-1.392,"[0.236, -0.701, -0.525, -0.423, -1.392]",0.260,-0.157,-0.418,-0.713,...,0.790,0.810,0.748,0.773,"[0.604, 0.79, 0.81, 0.748, 0.773]",-1.111,NaN,NaN,NaN,"[-0.14590661005217614, -1.1113513144455396, nan, nan, nan]"
ttr_OTHER,,-0.942,-0.641,-0.168,-0.276,"[-0.234, -0.942, -0.641, -0.168, -0.276]",-0.390,-0.477,-0.324,-0.355,...,1.039,0.720,0.473,0.849,"[1.086, 1.039, 0.72, 0.473, 0.849]",NaN,NaN,NaN,NaN,"[nan, nan, nan, nan, nan]"
ttr_VERB,,-0.332,-0.230,-0.291,-0.492,"[0.154, -0.332, -0.23, -0.291, -0.492]",0.443,-0.110,-0.237,-0.484,...,0.106,0.422,0.535,0.499,"[-0.011, 0.106, 0.422, 0.535, 0.499]",1.430,NaN,NaN,NaN,"[nan, 1.4301306759330685, nan, nan, nan]"
ttr_mean,,0.796,0.127,-0.599,-0.220,"[-0.452, 0.796, 0.127, -0.599, -0.22]",0.155,-0.292,-0.345,-0.487,...,0.360,0.534,0.646,0.857,"[0.248, 0.36, 0.534, 0.646, 0.857]",-0.843,NaN,NaN,NaN,"[0.2359642397432712, -0.842678914530909, nan, nan, nan]"

In [ ]:
stopx

In [9]:
# d_models

In [3]:
# groups_train = COMPARISONS[0]
# # cdf_preds, cdf_feats, cd_models = classify_then_predict_group(groups_train,return_models=True,num_runs=10)
# groups_train

In [8]:
# cdf_preds, cdf_feats, cd_models = classify_then_predict_comparisons(COMPARISONS,return_models=True,num_runs=1)

In [9]:
# cdf_feats

In [10]:
# cdf_preds

In [11]:
# cdf_preds['disc'] = [x.split('/')[0] for x in cdf_preds.index]
# cdf_preds.groupby(['predict_type','disc','comparison']).mean(numeric_only=True).sort_values('prob_Philosophy',ascending=False).dropna()

In [12]:
# cdf_feats.groupby('feature').mean(numeric_only=True).sort_values('weight',ascending=False)

NameError: name 'get_preds_feats' is not defined

In [2]:
# df_preds, df_feats, d_models = get_preds_feats()#COMPARISONS[:1], num_runs=1, sample_size=100,_force=True) #COMPARISONS[:1], feat_types=['deprel'], num_runs=1, verbose=True)

In [3]:
df_preds['accuracy'] = pd.to_numeric(df_preds.accuracy, errors='coerce')
df_preds[df_preds.predict_type=="cv"].groupby('comparison')['accuracy'].mean()

NameError: name 'pd' is not defined

In [4]:
df_feats

NameError: name 'df_feats' is not defined

In [5]:
df_feats['weight_abs'] = df_feats['weight'].abs()
df_feats.groupby('feat_type').mean(numeric_only=True).T

NameError: name 'df_feats' is not defined

In [6]:
stopxx

NameError: name 'stopxx' is not defined

In [3]:
# COMPARISONS

In [4]:
get_all_feats()

,sent_height,sent_num_words_in_dependent_clauses,sent_num_words_in_independent_clauses,sent_num_independent_clauses,sent_num_dependent_clauses,pos_IN,pos_NN,pos_JJ,pos_DT,"pos_,",...,deprel_discourse,deprel_vocative,pos_NFP,deprel_reparandum,deprel_csubj:outer,pos_SYM,deprel_orphan,deprel_goeswith,pos_AFX,pos_GW
id,,,,,,,,,,,,,,,,,,,,,
phil/10.2307/20111773__02,-0.390519,1.289891,-1.289891,-0.438993,1.207121,-0.070315,-1.706248,1.166067,-0.189528,1.310370,...,-0.595155,-0.367178,-0.226858,-0.470208,-0.218157,-0.216717,-0.169213,-0.026484,-0.06553,-0.033107
phil/10.2307/2379466__05,0.505629,1.583164,-1.583164,-0.492482,1.049130,0.117227,-0.279952,0.037163,-0.664539,-0.569395,...,-0.595155,-0.367178,-0.226858,-0.470208,-0.218157,-0.216717,-0.169213,-0.026484,-0.06553,-0.033107
lit/468313__05,-0.057800,-1.719735,1.719735,-0.290963,-1.893383,0.846476,0.914787,1.807776,1.373787,-0.438296,...,-0.595155,-0.367178,-0.226858,-0.470208,-0.218157,-0.216717,-0.169213,-0.026484,-0.06553,-0.033107
lit/509517__01,-1.455944,-0.562000,0.562000,-1.981948,-0.774074,-1.163708,-2.174687,-0.831309,-0.953964,2.221545,...,0.830386,3.978197,-0.226858,-0.470208,-0.218157,-0.216717,-0.169213,-0.026484,-0.06553,-0.033107
phil/10.2307/20140633__02,1.184079,1.028434,-1.028434,-0.616117,1.458713,-0.240151,0.068870,-0.083296,0.334014,-1.232474,...,0.443319,-0.367178,-0.226858,-0.470208,-0.218157,-0.216717,-0.169213,-0.026484,-0.06553,-0.033107
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
lit/30031939__01,-0.658682,-0.668491,0.668491,-1.020335,-0.737950,0.088091,-0.644223,0.747319,-0.659211,0.702166,...,-0.595155,-0.367178,-0.226858,-0.470208,-0.218157,-0.216717,-0.169213,-0.026484,-0.06553,-0.033107
phil/10.2307/2025409__04,0.481351,0.784142,-0.784142,0.266945,1.414832,-0.295978,-0.108302,-1.613020,0.063557,-0.108531,...,0.888847,-0.367178,-0.226858,-0.470208,-0.218157,-0.216717,-0.169213,-0.026484,-0.06553,-0.033107
phil/10.2307/2953730__03,1.122135,1.146417,-1.146417,-0.129505,1.833654,-0.538900,-0.544265,-1.380551,-1.149295,0.113526,...,-0.595155,-0.367178,-0.226858,-0.470208,-0.218157,-0.216717,-0.169213,-0.026484,-0.06553,-0.033107
lit/468421__06,-1.064896,-0.278295,0.278295,0.217638,-0.716220,-0.071856,0.649515,-0.145008,0.883376,0.509359,...,0.462582,-0.367178,-0.226858,-0.470208,-0.218157,-0.216717,-0.169213,-0.026484,-0.06553,-0.033107
phil/10.2307/2185617__06,0.865627,0.044130,-0.044130,1.067236,0.609709,1.904250,0.010231,-0.816354,-0.676448,-0.460911,...,-0.053499,-0.367178,-0.226858,-0.470208,-0.218157,-0.216717,5.909973,-0.026484,-0.06553,-0.033107

In [ ]:
# df_preds, df_feats, d_models = get_preds_feats(_force=True)
df_preds, df_feats, d_models = get_preds_feats(num_runs=1)

## 1900-1925 Philosophy vs 1900-1925 Literature

getting target for cv data: 100%|██████████| 33666/33666 [00:00<00:00, 40133.14it/s]
getting target for cv data: 100%|██████████| 1382/1382 [00:00<00:00, 43247.02it/s]
getting target for cv data: 100%|██████████| 752/752 [00:00<00:00, 42145.36it/s]

Index(['sent_height', 'sent_num_words_in_dependent_clauses',
       'sent_num_words_in_independent_clauses', 'sent_num_independent_clauses',
       'sent_num_dependent_clauses', 'pos_IN', 'pos_NN', 'pos_JJ', 'pos_DT',
       'pos_,', 'pos_RB', 'pos_VBZ', 'pos_PRP', 'pos_NNS', 'pos_CC', 'pos_.',
       'pos_VBN', 'pos_VB', 'pos_VBP', 'pos_NNP', 'pos_WDT', 'pos_VBG',
       'pos_MD', 'pos_CD', 'pos_TO', 'pos_PRP$', 'pos_EX', 'pos_POS', 'pos_WP',
       'pos_-LRB-', 'pos_-RRB-', 'pos_VBD', 'pos_:', 'pos_FW', 'pos_RP',
       'pos_WRB', 'pos_HYPH', 'pos_NNPS', 'deprel_punct', 'deprel_case',
       'deprel_det', 'deprel_nsubj', 'deprel_amod', 'deprel_advmod',
       'deprel_mark', 'deprel_obl', 'deprel_nmod', 'deprel_cc', 'deprel_root',
       'deprel_conj', 'deprel_cop', 'deprel_advcl', 'deprel_obj',
       'deprel_acl:relcl', 'deprel_aux:pass', 'deprel_ccomp', 'deprel_aux',
       'deprel_nsubj:pass', 'deprel_xcomp', 'deprel_nmod:poss', 'deprel_expl',
       'deprel_acl', 'deprel_fixed', 'deprel_compound', 'deprel_nummod',
       'deprel_appos', 'deprel_parataxis', 'deprel_obl:agent',
       'deprel_compound:prt', 'deprel_dep', 'deprel_nsubj:outer',
       'deprel_csubj', 'deprel_obl:unmarked', 'deprel_nmod:unmarked',
       'deprel_cc:preconj', 'deprel_dislocated', 'pos_JJS', 'pos_RBR',
       'pos_PDT', 'pos_JJR', 'deprel_det:predet', 'deprel_iobj',
       'deprel_csubj:pass', 'pos_RBS', 'deprel_advcl:relcl', 'pos_UH',
       'pos_WP$', 'deprel_discourse', 'deprel_vocative', 'pos_NFP',
       'deprel_reparandum', 'deprel_csubj:outer', 'pos_SYM', 'deprel_orphan',
       'deprel_goeswith', 'pos_AFX', 'pos_GW', '_target'],
      dtype='object')

100%|██████████| 1/1 [00:08<00:00,  8.83s/it]
getting target for cv data: 100%|██████████| 33666/33666 [00:00<00:00, 37950.67it/s]
getting target for cv data: 100%|██████████| 1382/1382 [00:00<00:00, 39813.51it/s]
getting target for cv data: 100%|██████████| 752/752 [00:00<00:00, 42107.10it/s]
getting target for cv data: 100%|██████████| 33666/33666 [00:00<00:00, 39543.92it/s]
getting target for cv data: 100%|██████████| 1382/1382 [00:00<00:00, 37423.27it/s]
getting target for cv data: 100%|██████████| 752/752 [00:00<00:00, 39847.35it/s]

## 1925-1950 Philosophy vs 1925-1950 Literature

getting target for cv data: 100%|██████████| 33666/33666 [00:00<00:00, 41019.38it/s]
getting target for cv data: 100%|██████████| 2250/2250 [00:00<00:00, 42791.26it/s]
getting target for cv data: 100%|██████████| 1359/1359 [00:00<00:00, 42415.57it/s]

Index(['sent_height', 'sent_num_words_in_dependent_clauses',
       'sent_num_words_in_independent_clauses', 'sent_num_independent_clauses',
       'sent_num_dependent_clauses', 'pos_IN', 'pos_NN', 'pos_JJ', 'pos_DT',
       'pos_,', 'pos_RB', 'pos_VBZ', 'pos_PRP', 'pos_NNS', 'pos_CC', 'pos_.',
       'pos_VBN', 'pos_VB', 'pos_VBP', 'pos_NNP', 'pos_WDT', 'pos_VBG',
       'pos_MD', 'pos_CD', 'pos_TO', 'pos_PRP$', 'pos_EX', 'pos_POS', 'pos_WP',
       'pos_-LRB-', 'pos_-RRB-', 'pos_VBD', 'pos_:', 'pos_FW', 'pos_RP',
       'pos_WRB', 'pos_HYPH', 'pos_NNPS', 'deprel_punct', 'deprel_case',
       'deprel_det', 'deprel_nsubj', 'deprel_amod', 'deprel_advmod',
       'deprel_mark', 'deprel_obl', 'deprel_nmod', 'deprel_cc', 'deprel_root',
       'deprel_conj', 'deprel_cop', 'deprel_advcl', 'deprel_obj',
       'deprel_acl:relcl', 'deprel_aux:pass', 'deprel_ccomp', 'deprel_aux',
       'deprel_nsubj:pass', 'deprel_xcomp', 'deprel_nmod:poss', 'deprel_expl',
       'deprel_acl', 'deprel_fixed', 'deprel_compound', 'deprel_nummod',
       'deprel_appos', 'deprel_parataxis', 'deprel_obl:agent',
       'deprel_compound:prt', 'deprel_dep', 'deprel_nsubj:outer',
       'deprel_csubj', 'deprel_obl:unmarked', 'deprel_nmod:unmarked',
       'deprel_cc:preconj', 'deprel_dislocated', 'pos_JJS', 'pos_RBR',
       'pos_PDT', 'pos_JJR', 'deprel_det:predet', 'deprel_iobj',
       'deprel_csubj:pass', 'pos_RBS', 'deprel_advcl:relcl', 'pos_UH',
       'pos_WP$', 'deprel_discourse', 'deprel_vocative', 'pos_NFP',
       'deprel_reparandum', 'deprel_csubj:outer', 'pos_SYM', 'deprel_orphan',
       'deprel_goeswith', 'pos_AFX', 'pos_GW', '_target'],
      dtype='object')

100%|██████████| 1/1 [00:09<00:00,  9.17s/it]
getting target for cv data:  24%|██▎       | 7969/33666 [00:00<00:00, 39955.18it/s]

In [ ]:
# pd.options.display.max_rows = 10

df_preds[df_preds.predict_type=="unseen"].groupby(['true_label','comparison']).size()

true_label  comparison
Literature  1900-1925 Philosophy vs 1900-1925 Literature    104540
            1925-1950 Philosophy vs 1925-1950 Literature     98470
            1950-1975 Philosophy vs 1950-1975 Literature     89900
            1975-2000 Philosophy vs 1975-2000 Literature     74370
            2000-2025 Philosophy vs 2000-2025 Literature     80960
Philosophy  1900-1925 Philosophy vs 1900-1925 Literature    217080
            1925-1950 Philosophy vs 1925-1950 Literature    211010
            1950-1975 Philosophy vs 1950-1975 Literature    202440
            1975-2000 Philosophy vs 1975-2000 Literature    186910
            2000-2025 Philosophy vs 2000-2025 Literature    193500
dtype: int64

In [ ]:
df_preds.groupby(['true_label','comparison']).mean(numeric_only=True)

                                                         prob_Literature  \
true_label comparison
Literature 1925-1950 Philosophy vs 1925-1950 Literature         0.703004
           1950-1975 Philosophy vs 1950-1975 Literature         0.806158
           1975-2000 Philosophy vs 1975-2000 Literature         0.855432
...                                                                  ...
Philosophy 1950-1975 Philosophy vs 1950-1975 Literature         0.119285
           1975-2000 Philosophy vs 1975-2000 Literature         0.148399
           2000-2025 Philosophy vs 2000-2025 Literature         0.177212

                                                         prob_Philosophy  \
true_label comparison
Literature 1925-1950 Philosophy vs 1925-1950 Literature         0.296996
           1950-1975 Philosophy vs 1950-1975 Literature         0.193842
           1975-2000 Philosophy vs 1975-2000 Literature         0.144568
...                                                                  ...
Philosophy 1950-1975 Philosophy vs 1950-1975 Literature         0.880715
           1975-2000 Philosophy vs 1975-2000 Literature         0.851601
           2000-2025 Philosophy vs 2000-2025 Literature         0.822788

                                                         confidence   correct  \
true_label comparison
Literature 1925-1950 Philosophy vs 1925-1950 Literature    0.935896  0.090342
           1950-1975 Philosophy vs 1950-1975 Literature    0.916418  0.097056
           1975-2000 Philosophy vs 1975-2000 Literature    0.920154  0.117619
...                                                             ...       ...
Philosophy 1950-1975 Philosophy vs 1950-1975 Literature    0.913937  0.045076
           1975-2000 Philosophy vs 1975-2000 Literature    0.919787  0.048992
           2000-2025 Philosophy vs 2000-2025 Literature    0.949721  0.048582

                                                         accuracy  support  \
true_label comparison
Literature 1925-1950 Philosophy vs 1925-1950 Literature   0.91600   2000.0
           1950-1975 Philosophy vs 1950-1975 Literature   0.89595   2000.0
           1975-2000 Philosophy vs 1975-2000 Literature   0.90045   2000.0
...                                                           ...      ...
Philosophy 1950-1975 Philosophy vs 1950-1975 Literature   0.89595   2000.0
           1975-2000 Philosophy vs 1975-2000 Literature   0.90045   2000.0
           2000-2025 Philosophy vs 2000-2025 Literature   0.92640   2000.0

                                                         run
true_label comparison
Literature 1925-1950 Philosophy vs 1925-1950 Literature  4.5
           1950-1975 Philosophy vs 1950-1975 Literature  4.5
           1975-2000 Philosophy vs 1975-2000 Literature  4.5
...                                                      ...
Philosophy 1950-1975 Philosophy vs 1950-1975 Literature  4.5
           1975-2000 Philosophy vs 1975-2000 Literature  4.5
           2000-2025 Philosophy vs 2000-2025 Literature  4.5

[8 rows x 7 columns]

In [ ]:
df_preds

,true_label,pred_label,prob_Literature,prob_Philosophy,test_label,confidence,correct,accuracy,support,run,predict_type,comparison
id,,,,,,,,,,,,
lit/458348__02,Literature,Literature,0.908500,0.091500,Literature / Philosophy,0.908500,1,0.9155,2000.0,0,cv,1925-1950 Philosophy vs 1925-1950 Literature
lit/457860__02,Literature,Literature,0.974676,0.025324,Literature / Philosophy,0.974676,1,0.9155,2000.0,0,cv,1925-1950 Philosophy vs 1925-1950 Literature
lit/459316__04,Literature,Literature,0.999719,0.000281,Literature / Philosophy,0.999719,1,0.9155,2000.0,0,cv,1925-1950 Philosophy vs 1925-1950 Literature
...,...,...,...,...,...,...,...,...,...,...,...,...
phil/10.2307/2953730__03,Philosophy,NaN,0.017091,0.982909,Literature / Philosophy,NaN,0,NaN,NaN,9,unseen,2000-2025 Philosophy vs 2000-2025 Literature
lit/468421__06,Literature,NaN,0.029168,0.970832,Literature / Philosophy,NaN,0,NaN,NaN,9,unseen,2000-2025 Philosophy vs 2000-2025 Literature
phil/10.2307/2185617__06,Philosophy,NaN,0.419604,0.580396,Literature / Philosophy,NaN,0,NaN,NaN,9,unseen,2000-2025 Philosophy vs 2000-2025 Literature

In [ ]:
# df_preds, df_feats, d_models = classify_then_predict_comparisons(
#     COMPARISONS,
#     num_runs=10,
#     sample_size=1000,
#     feat_n=50,
#     feat_n_egs=10,
#     verbose=False,
#     return_models=True,
#     normalize=False,
# )

# df_preds, df_feats, d_models = get_preds_feats()

In [ ]:
# df_preds

In [ ]:
df_preds, df_feats, d_models = get_preds_feats()

In [ ]:
df_feats[['feature','weight','score_mean1','score_z1']].sort_values('weight',ascending=False).head(10)

              feature    weight  score_mean1   score_z1
58             pos_FW  0.924665     0.821637   0.827107
58             pos_FW  0.851065     0.980653   0.995061
58             pos_FW  0.511805     0.907464   0.939736
..                ...       ...          ...        ...
44  deprel_reparandum  0.262088     0.321187   0.330648
23   deprel_discourse  0.251378     0.934904   0.950481
54             pos_CC  0.225784    33.694057  33.634660

[10 rows x 4 columns]

In [ ]:
newtext= """By a `denoting phrase' I mean a phrase such as any one of the following: a man, some man, any man, every man, all men, the present King of England, the presenting King of France, the center of mass of the solar system at the first instant of the twentieth century, the revolution of the earth round the sun, the revolution of the sun round the earth. Thus a phrase is denoting solely in virtue of its form. We may distinguish three cases: (1) A phrase may be denoting, and yet not denote anything; e.g., `the present King of France'. (2) A phrase may denote one definite object; e.g., `the present King of England' denotes a certain man. (3) A phrase may denote ambiguously; e.g. `a man' denotes not many men, but an ambiguous man. The interpretation of such phrases is a matter of considerably difficulty; indeed, it is very hard to frame any theory not susceptible of formal refutation. All the difficulties with which I am acquainted are met, so far as I can discover, by the theory which I am about to explain."""

doc = get_nlp_doc(newtext)

In [ ]:
df_new_preds, df_new_feats = get_new_preds_feats(doc)

In [ ]:
df_new_feats.groupby('feature').mean(numeric_only=True)[['weight','score_mean1','score_mean2','score_mean3','score_mean_div_3-1','score_mean_div_3-2']].sort_values('score_mean_div_3-2',ascending=True).sample(5)

,weight,score_mean1,score_mean2,score_mean3,score_mean_div_3-1,score_mean_div_3-2
feature,,,,,,
deprel_expl,-0.076533,5.746964,3.089669,4.385965,0.764007,1.463939
pos_FW,0.614853,0.853004,0.260762,13.157895,15.666947,59.372368
sent_num_words_in_independent_clauses,0.007595,374.365766,526.388508,934.210526,2.508512,1.777253
deprel_csubj,-0.104341,2.359387,1.337220,4.385965,1.881202,3.298811
pos_JJS,-0.080529,1.355949,1.368312,0.000000,0.000000,0.000000

In [ ]:
df_new_preds.mean(numeric_only=True)

run      4.50000
prob1    0.22055
prob2    0.77945
dtype: float64

In [ ]:
df_preds

,true_label,pred_label,prob1,prob2,test_label,confidence,correct,accuracy,support,run,predict_type,prob_Literature,prob_Philosophy,comparison
id,,,,,,,,,,,,,,
lit/3716491__04,Literature,Philosophy,0.49144014963593696,0.508559850364063,Literature / Philosophy,0.508559850364063,0,0.9145,2000.0,0,cv,nan,nan,1925-1950 Philosophy vs 1925-1950 Literature
lit/2871701__01,Literature,Literature,0.9991263267257862,0.000873673274213794,Literature / Philosophy,0.9991263267257862,1,0.9145,2000.0,0,cv,nan,nan,1925-1950 Philosophy vs 1925-1950 Literature
lit/457453__01,Literature,Literature,0.9974224957261134,0.0025775042738865593,Literature / Philosophy,0.9974224957261134,1,0.9145,2000.0,0,cv,nan,nan,1925-1950 Philosophy vs 1925-1950 Literature
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
phil/10.2307/2953730__03,Philosophy,prob_Philosophy,nan,nan,Literature / Philosophy,nan,0,nan,nan,9,unseen,0.012841101948878997,0.987158898051121,2000-2025 Philosophy vs 2000-2025 Literature
lit/468421__06,Literature,prob_Philosophy,nan,nan,Literature / Philosophy,nan,0,nan,nan,9,unseen,0.1272485323519187,0.8727514676480813,2000-2025 Philosophy vs 2000-2025 Literature
phil/10.2307/2185617__06,Philosophy,prob_Philosophy,nan,nan,Literature / Philosophy,nan,0,nan,nan,9,unseen,0.3808832762297668,0.6191167237702332,2000-2025 Philosophy vs 2000-2025 Literature